#!/bin/bash

#@file
# Sets up the configs for my setup specifically

# Libs
source ${HOME}/.bash_functions/msgs
source ${HOME}/.bash_functions/get_site


# Settings
sites=${HOME}/Sites
site_name=$(get_site)
config=${sites}/${site_name}/config
fed_port="8080"
fedora="fedora"
if [ "${site_name}" == "tufts-image-library" ]; then
  solr="solr/mira"
else
  solr="solr/${site_name}"
fi

# Checks
if [ -z "${site_name}" ]; then
  bad_msg "Sites are in ${sites}. You seem to be in an invalid directory."
  exit 1
fi

rake -n >/dev/null 2>/dev/null
if [ ${?} -gt 0 ]; then
  bad_msg "Rake isn't working. Are you in a rails installation?"
  exit 1
fi

# Helpers
function copy_sample_files {
  if [ -z "${1}" ]; then
    bad_msg "You gotta give me a path."
    return 1
  fi

  # The for loop below throws an error if there's nothing to loop through.
  if [ -z "$(find ${1} -name '*.sample')" ]; then
    return 0
  fi

  for config_file in ${1}/*.sample
  do
    sample_file=${config_file##*/}
    dest_file=${sample_file%.sample}
    cp ${config_file} ${1}/${dest_file}
  done
}

# Process
rake config:copy
if [ ${?} -gt 0 ]; then
  neutral_msg "Rake config:copy failed. Doing it manually."
  copy_sample_files ${config}
  copy_sample_files ${config}/initializers
# rake config:copy works on mira, but it doesnt' copy the application.yml file.
elif [ "${site_name}" == "mira" ]; then
  cp ${config}/application.yml.sample ${config}/application.yml
fi

# Point fedora/solr to our local installations, instead of pre-packaged jetty.
sed -i '' "s:898[[:digit:]]/fedora:${fed_port}/${fedora}:g" ${config}/fedora.yml
sed -i '' "s:solr/development:${solr}:g" ${config}/solr.yml
sed -i '' "s:solr/development:${solr}:g" ${config}/blacklight.yml
sed -i '' "s:solr/blacklight-core:${solr}:g" ${config}/blacklight.yml

# I don't know what having brian's email does in application.yml but might as well change it.
sed -i '' "s:brian.goodmon:travis.lilleberg:g" ${config}/application.yml

# Trove's object store needs to point to mira.
if [ "${site_name}" == "trove" ]; then
  sed -i '' "s:/tmp/local_object_store:/../mira/tmp/local_object_store:g" ${config}/application.yml
fi

