#!/bin/bash

#@file
#Manages the solr cores

# Libs
source ~/.bash_functions/get_site


# Settings
solr_script="${HOME}/.apps/solr6"

if [ "${2}" == "this" ]; then
  core_name=$(get_site)
elif [ "${2}" == "test" ]; then
  core_name=$(get_site)-test
else
  core_name="${2}"
fi



# Gooo
case "${1}" in
  'is_running')
    ${solr_script} is_running
    ;;

  'start')
    ${solr_script} start
    ;;

  'stop')
    ${solr_script} stop
    ;;

  'restart')
    ${solr_script} restart
    ;;

  'create')
    if [ -z "${core_name}" ]; then
      exit 1
    fi
    ${solr_script} create $core_name $3
    ;;

  'destroy')
    if [ -z "${core_name}" ]; then
      exit 1
    fi
    ${solr_script} destroy $core_name
    ;;

  'list')
    ${solr_script} list
    ;;

  'clear')
    if [ -z "${core_name}" ]; then
      exit 1
    fi
    ${solr_script} clear $core_name
    ;;

esac

