#!/bin/bash

#@file
#Manages the solr cores

# Libs
source ~/.bash_functions/msgs
source ~/.bash_functions/get_site


# Settings
solr_root="/usr/local/solr"
solr_home="${solr_root}/server/solr"
solr_script="${solr_root}/bin/solr"

if [ "${2}" == "this" ]; then
  core_name=$(get_site)
  if [ -z "${core_name}" ]; then
    exit 1
  fi
else
  core_name="${2}"
fi

core=${solr_home}/${core_name}
err="First argument should be 'create', 'destroy', or 'list'.
  Second argument should be core name.
  Third argument is optional conf folder for core."
solr_url="localhost:8983/solr/${core_name}"


# Gooo
case "${1}" in
  'start')
    ${solr_script} start
    ;;

  'stop')
    ${solr_script} stop
    ;;

  'restart')
    ${solr_script} restart
    ;;

  'create')
    if [ -z "${2}" ]; then
      bad_msg "${err}"
      exit 1
    fi

    if [ -e ${core} ]; then
      bad_msg "${core} already exists as a Solr core."
      exit 1
    fi

    if [ ! -z ${3} ]; then
      if [ ! -d ${3} ]; then
        bad_msg "${3} is not a directory."
        exit 1
      fi
      solr_conf=${3}
    fi

    good_msg "Creating the new Solr core."


    ${solr_script} create -c ${core_name}
    cp ${solr_conf}/* ${core}/conf
    ${solr_script} restart
    ;;

  'destroy')
    if [ -z "${2}" ]; then
      bad_msg "${err}"
      exit 1
    fi

    if [ ! -d ${core} ]; then
      bad_msg "${2} isn't a Solr core."
      exit 1
    fi

    good_msg "Destroying the ${2} Solr core."
    ${solr_script} delete -c ${core_name}
    ${solr_script} restart
    ;;

  'list')
    echo
    ignore="configsets"
    for this_dir in $(find $solr_home -type d -maxdepth 1)
    do
      if [ "${this_dir}" == "${solr_home}" ]; then
        continue
      fi
      rel_dir=${this_dir#$solr_home/}
      if [ "${ignore}" == "${ignore/$rel_dir/}" ]; then
        echo "${rel_dir}"
      fi
    done
    echo
    ;;

  'clear')
    if [ -z "${2}" ]; then
      bad_msg "${err}"
      exit 1
    fi

    if [ ! -d ${core} ]; then
      bad_msg "${2} isn't a Solr core."
      exit 1
    fi
    echo
    target="${solr_url}/update?stream.body=<delete><query>*:*</query></delete>&commit=true"
    good_msg "Clearing ${core_name}."
    curl $target
    echo
    ;;

  *)
    bad_msg "${err}"
    exit 1
    ;;
esac
