#!/bin/bash

#@file
#Turns Tomcat on and off

source ~/.bash_functions/msgs

tom_path="/Library/Tomcat/"

case "${1}" in
  'start')
    if [ $(tc running) -eq 0 ]; then
#      cd /Library/Tomcat/logs
      ${tom_path}/bin/startup.sh
      /usr/local/solr/bin/solr start
    fi
    ;;

  'stop')
    if [ $(tc running) -gt 0 ]; then
      ${tom_path}/bin/shutdown.sh
      /usr/local/solr/bin/solr stop
    fi
    ;;

  'restart')
    tc stop
    sleep 3
    tc start
    ;;

  'running')
    if [ ! -z "$(ps aux | grep tomcat | grep -v grep)" ]; then
      echo 1
    else
      echo 0
    fi
    ;;

  *)
    bad_msg "Gotta say 'start', 'stop', 'restart', or 'running'."
    ;;
esac

