#!/bin/bash

#@file
# Pulls my config-files branch and updates it with my latest config files


# Libs
source ~/.bash_functions/msgs


# Checks
if [ -z "${1}" ]; then
  bad_msg "You gotta give me a git commit message."
  exit 1
fi


# Settings
target_files=("bash_profile" "vimrc" "bash_colors")


# Goooo
good_msg "Updating your config repostitory!"

gh travisLilleberg/config-files

cd config-files
for filename in "${target_files[@]}"
do
  cp ${HOME}/.${filename} ${filename}
done

git add .
git commit -m"${1}"
git push

cd ..
sudo rm -r config-files

